cms-l1t-offline/cms-l1t-analysis

Makefile
This guarantees that missing files are always downloaded when you run `make setup`
=> Changes to Makefile to pull data files as proper makefile targets

Makefile
Not sure why exactly, but when I ran just `make`, the `setup` target had problems because the `build` directory wasn't being correctly created.  This solves the problem.
=> Changes to makefile

.gitignore, Makefile
Tiny changes to the gitignore file for the project to ignore emacs and vim swap files.
Should be merged after #12.
=> Ignore vim and emacs backup files

cmsl1t/geometry.py
This is useful for some PUS schemes which account for the different Eta widths.
I might be duplicating code here, since I'm guessing something like this is available in cmssw already.  If so, could someone point me to it and I'll close this?
=> Add the tower widths in eta to geometry.

cmsl1t/utils/root_glob.py, test/utils/test_root_glob.py
This adds an implementation of `root_glob` which extends python's `glob` module to work over remote file systems.  It's based heavily on the way TChain handles wildcards, and as such has the same shortcoming, that only wild-cards in the basename are handled, and not in any directory name.
We can expand this in the future, to make things more like full globbing (which needs some recursion as python `glob` does) but my goal is to give us something that works for now.   I'll also put up a PR for this on rootpy so hopefully we can actually remove this in the future.
Should fix issue #16
=> Add first working version of a root_glob object

bin/analyze, cmsl1t/analyzers/BaseAnalyzer.py, cmsl1t/analyzers/demo_analyzer.py
This adds several additional files, with the aim of being a first step towards the sort of interface a new student might want to work with to analyze things. 
This PR adds:
- An overall `analyze` file, which in general would not need to be changed.
- A `BaseAnalyzer` module which provides the generic interface for an analyzer.  
- A demo of how a user would implement an analyzer (`demo_analyzer`).
To run analysis using a specific custom analyzer, the command line (for now) would be:
```bash
python bin/analyze -a demo_analyzer -i 'data/L1Ntuple_*.root' -n 1000
```
I've set up the minimal set of command line options that one would need to use this for now:
```
$ python bin/analyze -h 
usage: analyze [-h] [-o OUT_DIR] [-c CONFIG] -a ANALYSIS [-n N_EVENTS] [-r] -i INPUTS
optional arguments: …
```
=> Add an initial draft of the sort of 'analyzer' I would suggest we use

bin/analyze, cmsl1t/utils/timers.py, test/utils/test_timers.py
The timerfunc decorator was supposed to be able to be used with no arguments, or provided a single argument being a print_function to specify a log output.  Since such behaviour is hard to achieve in python, and since this was giving us grief elsewhere I have split this decorator into two, one which takes no arguments, and just uses python's `print` method, and one called `timerfunc_log_to` which receives on argument for the printer method to use.
This allows a fix for issue #24.  
I've also extended the unit tests to check this is working.
=> Split timerfunc decorator for different call-signatures

cmsl1t/hist/hist_collection.py, test/hist/test_histogramCollection.py
Some binning strategies produce overlapping bins (eg, eta regions in the detector).  In that case operations like:
```
some_hist_collection[key1, key2]
```
will return multiple histogram objects.  As a result, it is cumbersome to then do something like `fill()` since you need to call that on every histogram that's returned, which would look something like:
```
for hist in some_hist_collection[key1, key2]:
hist.fill(value)
```
This PR adds a `HistCollectionView` class, which wraps the returned lists so that instead of the above for loop you can just write:
```
some_hist_collection[key1, key2].fill(value)
```
=> Improve interface to allow working with multiple hists for one key

README.md, cmsl1t/__init__.py, cmsl1t/collections/by_pileup.py, cmsl1t/collections/efficiency.py, cmsl1t/collections/resolution.py, cmsl1t/io/__init__.py, docs/code.rst, docs/conf.py, docs/tutorial.rst
Currently, http://cms-l1t-analysis.readthedocs.io/en/latest/ is not building correctly as it fails to include `cmsl1t`.
This PR fixes the import, sorts the API docs and moves ROOT dependencies from import to run-time.
=> Fixes for documentation on readthedocs.

Makefile, README.md, cmsl1t/config.py, cmsl1t/utils/module.py, cmsl1t/utils/root_glob.py, config/demo.yaml, config/study_tower28_met.yaml, docs/code.rst, requirements.txt, test/test_config.py, test/utils/test_root_glob.py
In this PR I am adding validation functionality to the `cmsl1t.config.ConfigParser`.
This includes:
- unit tests for the config parser
- changes in the existing configs (2 had errors!)
- documentation describing the configuration
On the side I've also added `sphinx` and `pyfakefs` to the project requirements and added `grid_access` attribute to the unit tests. It is now possible to test remote file systems if grid access is available (e.g. a valid grid proxy exists) with `make test-all`.
=> Config validation

cmsl1t/config.py
At the moment, if a required section is missing in a config file, the validation seems to die without any explanation.  This should solve the issue.
=> Say something when validation fails due to missing section

cmsl1t/config.py, cmsl1t/playground/eventreader.py
Sometimes we produce L1NTuples without specific trees, eg emulated objects which may or may not be included.  The current implementation expects all trees to be there.  This change will allow, at least in the event-reader, trees not to be in the files but the program continue.  
Should only be merged after PR #42.
=> Handle L1NTuples without certain trees

cmsl1t/playground/eventreader.py
Dodgy pluralisation of variable names had caused confusion and errors... This fixes it.
=> Make {emuC,c}aloTowers pluralised consistently

cmsl1t/hist/hist_collection.py, cmsl1t/plotting/efficiency.py, cmsl1t/utils/draw.py, cmsl1t/utils/fit_efficiency.py
There was an issue before that the errors produced in the efficiency plotter were rubbish.  This fixes that by making proper use of TEfficiency.  
Previously I'd been nervous that there would be an issue when we try to combine the turn-ons produced in separate jobs eg. when running on the batch system.  Having looked into it though, this is taken care of by TEfficiency::Merge, so there should be no problem there.
I've also made sure the `fit_efficiency()` and `draw()` utilities can cope ok with this, before they were somewhat limited to the inputs that they could take.
=> Make proper use of TEfficiency

bin/cmsl1t, cmsl1t/analyzers/BaseAnalyzer.py, cmsl1t/analyzers/study_met.py, cmsl1t/config.py, cmsl1t/hist/hist_collection.py, cmsl1t/io/__init__.py, cmsl1t/plotting/base.py, cmsl1t/plotting/efficiency.py, config/demo.yaml
This implements the ability to have plotters restart from previously produced histograms, which is a key ingredient for running on the batch system, as well as making it easier to change the plot appearance.  
To implement this functionality, I've made changes to the output plot directory structure:
* Output root files containing histograms are stored under the output directory, made unique by a version number which is updated every time we run over n-tuples, (ie. each run without the `-r` option).
* Output plots are stored under a sub-directory of this, which is made unique for every execution by incrementing the plot version number.
* The config file parser now knows of the reload_histograms option and fills in a `hist_files` options on the `input` section, which is used to specify the …
=> Add the ability to reload histograms from files

Makefile, bin/cmsl1t, bin/cmsl1t_dirty_batch, cmsl1t/config.py, requirements.txt
Needs some modifications to the config parser.
To run it, simply give the config file you wish to use:
```
cmsl1t_dirty_batch -c <config_file>
```
The same config parser used for the `cmsl1t` command then parses the config, and then for each input file, a new config file is made with only that input file.  Intermediate scripts and histograms are stored under a sub-directory of the requested output directory, eg:
```
<output_dir>
└── batch-v1
├── _configs
│   ├── demo_0.yaml
│   ├── demo_1.yaml
│   └── demo_2.yaml
├── job_1
│   └── hist_file.root
├── job_2
│   └── hist_file.root
└── run_script.sh
```
Finally, once everything has been submitted the command needed to produce histograms is displayed (future improvements might optionally make this script wait and then automatically run the …
=> WIP: Add a dirty batch submission script, for issue #58

Makefile, bin/cmsl1t, bin/cmsl1t_dirty_batch, bin/get_l1Analysis, cmsl1t/config.py, requirements.txt
This builds off the work from PR #60 (which was merged prematurely :p ) to get batch system running.
Since I've had issues using the htcondor python bindings and testing things, I've implemented things using LSF and the bsub command for now.  I'm hoping @kreczko can implement the htcondor aspects in a later date.
With this PR, the full chain using the batch system feels in place.  We probably want to revisit the way we identify the output directory, since at the moment there is no knowledge of the batch system with cmsl1t itself (all batch system code is for the moment inside the new `cmsl1t_dirty_batch` command, hopefully this will be farmed out to better locations of the codebase in the near future).
See #60 for more details on how this works.  In addition, two new command line options …
=> Get bsub batch submission working

bin/env.sh
We need to guarantee certain package versions are used, and for this we use `pip install --user` however, we don't currently force that the directory used to install these packages is added to the PYTHONPATH variable. This PR fixes this.
Targeting weekly-checks, but should be ported to Master shortly as well.
=> Add users' site packages directory to PYTHONPATH

cmsl1t/utils/root_glob.py, test/utils/test_root_glob.py
I've back-ported the version of root_glob I added to central rootpy (and added our extra fixes, which should be pushed back to the rootpy version now as well...) so that we can put multiple globs in the filename paths.
Targeting this to weekly-checks branch but this should also be put onto master soon.
=> Allow multiple wildcards with root_glob

cmsl1t/hist/binning.py, cmsl1t/plotting/onlineVsOffline.py, cmsl1t/utils/draw.py
This adds the sort of generic plotter needed to complete the weekly-checks described on issue #65.  I've tested this on only a few events and it looks ok, and plots reasonable.  
This PR also fixes a small bug in the `Sorted` binning class, that impacted iterating over all bins.
To do before this is merged:
=> Add a generic 2D online vs offline quantity plotter

bin/cmsl1t, bin/cmsl1t_dirty_batch
This PR fixes the issue with click-log for cmsl1t_dirty_batch as documented on #71. 
In addition it fixes the cmsl1t command which had problems with the logging when more than 10 input files were given in the config.  It also adds the ability to send batch jobs with more than one input file per job, by providing an additional command line option to control this.
=> Fix issue 71 and other aspects of the bin/cmsl1t* commands

cmsl1t/analyzers/BaseAnalyzer.py, cmsl1t/plotting/base.py, cmsl1t/plotting/efficiency.py, cmsl1t/plotting/onlineVsOffline.py
A lack of returned objects in several of the methods involved with merging histograms together was causing an error message to be printed inappropriately.
=> Fix reporting of errors when merging histograms together 

cmsl1t/plotting/efficiency.py, test/plotting/test_efficiency.py
Our favourite plotter had (yet) another bug (!) where not all pile-up bins were being filled.
This extends the unit test coverage and fixes the issue.
=> Efficiency plots: Fill all pile-up bins

cmsl1t/plotting/efficiency.py, cmsl1t/plotting/onlineVsOffline.py, cmsl1t/plotting/resolution.py, cmsl1t/plotting/resolution_vs_X.py, cmsl1t/recalc/resolution.py, test/recalc/test_resolution.py
This PR adds:
* Recalc methods to deduce the resolution (difference between online and offline) for different quantities.
* A plotter to plot the resolution distribution vs pile-up
* A plotter to plot the resolution distributions against another variable (eg. eta or phi) in pile-up bins
=> Add two more plotters for resolution

bin/compile_l1Analysis, bin/create-map-file, bin/get_l1Analysis, bin/run_benchmark, cmsl1t/utils/module.py, config/ntuple_content.yaml
This PR refers to issue #79.
Overview:
A first version of the YAML format can be found here:
https://gist.github.com/kreczko/fcba8f6ca0f4229d83c43087f22b69c4#file-test-yaml
but it still contains plenty of duplicates (from the Emu vs normal trees):
https://gist.github.com/kreczko/fcba8f6ca0f4229d83c43087f22b69c4#file-duplicates
There are two possible solutions for default aliases:
1. Add Emu to the tree name (e.g. `event.L1EmuCaloTowerTree_CaloTP_ecalTPCaliphi`)
2. Add folder path to alias (e.g. `event.l1CaloTowerEmuTree_L1CaloTowerTree_CaloTP_ecalTPCaliphi`)
For the shorter version, this would probably be `event.emu_ecalTPCaliphi`
=> YAML NTuple config file for documentation and aliasing

Makefile, bin/cmsl1t_dirty_batch, bin/compile_l1Analysis, bin/get_l1Analysis, bin/run_benchmark
- fixed `make clean-so` (did not realise it was broken)
- replaced `#!/bin/env` with the more general `#!/usr/bin/env` (works now on both Debian and RedHat derivatives)
=> Minor fixes for Makefile and bin/*

.readthedocs.yml, environment.yml
Fixes https://readthedocs.org/projects/cms-l1t-analysis/builds/6175669/
Adds readthedocs configuration (`.readthedocs.yml`) and a conda `environment.yml` to  enable a conda build of the docs (includes ROOT).
=> Fixing the readthedocs errors

.dockerignore, .travis.yml, bin/env.sh, ci/Dockerfile, ci/test.sh, conda_requirements.txt, docker-compose.yaml, docker/Dockerfile, docker/cdw, requirements.txt
- fixes some docker issues (X11, missing library, terminal size)
- fixes conda requirements
- fixes pip requirements
For the latter: pyfakefs has removed `fake_filesystem_glob` starting version 3.3 (see https://github.com/jmcgeheeiv/pyfakefs/blob/master/CHANGES.md) so I fixed it to version 3.2 for now.
=> After the long slumber, cmsl1t wakes up

bin/cmsl1t_batch, bin/cmsl1t_batch_resubmit, bin/cmsl1t_batch_status, bin/cmsl1t_dirty_batch, cmsl1t/__init__.py, cmsl1t/batch/__init__.py, cmsl1t/batch/common.py, cmsl1t/batch/condor.py, cmsl1t/batch/lsf.py, requirements.txt, test/batch/mock_bjobs, test/batch/test_condor.py, test/batch/test_lsf.py
Fixes #99
The plan here is to:
- minimally enhance `cmsl1t_dirty_batch` to provide extra information needed
I intend to add, where possible, the extra information as `<path to batch dir>/info.csv` which can be used for versioning. E.g. status and resubmit scripts would read that file first to determine paths, etc (should allow for easier versioning).
=> A "cleaner" batch submission

cmsl1t/math.py
Missing conversion of reversed cumulative hist contents into array.
=> Convert output of cum sum back to array to build cum hist

cmsl1t/analyzers/jetMet_analyzer.py
A few small bug fixes:
- Wrong indentation for caloJet efficiencies, was only being filled when no matching caloEmuJet
- Correction to logic when assigning thresholds to emulator objects to fix edge case for METBE
As of this PR, the master branch reproduces the exact results of the updateFilters branch! 8)
=> Fix calo jets efficiencies and logic for emulator thresholds

.dockerignore, .travis.yml, ci/Dockerfile, ci/base/Dockerfile
Currently, the travis build takes 17 minutes to execute, of which 580s is spent on building the CI image.
I've moved the creation of the conda ENV from `ci` to `ci-base` which should be now a simple download.
Modifications are only executed if `conda_requirements.txt` or `requirements.txt` differ w.r.t. what is in the base image
=> Speeding up docker build for travis

QUICKSTART.md, bin/cmsl1t, cmsl1t/analyzers/jetMet_analyzer.py, cmsl1t/playground/eventreader.py, config/all2017.yaml, config/demo.yaml, config/efficiencies.yaml, config/energy_sums_efficiencies.yaml, config/gen.yaml, config/jet_efficiencies.yaml, config/jet_rates.yaml, config/jet_resolutions.yaml, config/offline_met_studies.yaml, config/rateVsPU.yaml, config/rates.yaml, config/study_tower28_met.yaml, config/weekly_checks.yaml, docs/tutorial/quickstart.rst
Relates to #122 ([comment](https://github.com/cms-l1t-offline/cms-l1t-analysis/pull/122#discussion_r184121668)).
Replaces 
```yaml
analysis:
- do_emu: False
-  do_reco: True
-  do_vertex: False
-  do_gen: False
```
with
```yaml
analysis:
load_trees:
- event
- upgrade
- recoTree
```
@bundocka would you be so kind to run one of your configs from this branch to check all is as expected?
=> Replacing `do_X` with `load_trees` in configs, analysers and eventReader

cmsl1t/analyzers/HW_Emu_jetMet_rates.py, config/efficiencies.yaml, config/gen.yaml, config/rateVsPU.yaml, config/rates.yaml
- Separates central and forward jets in HW_Emu_jetMet_rates.py so that fixed rate turn on comparisons make sense. 
- Updates configs to have separate thresholds for central and forward jets
=> Separate central and forward jets for fixed rate comparisons

cmsl1t/analyzers/jetMet_analyzer.py, cmsl1t/plotting/efficiency.py, conda_requirements.txt
- Add _dynamic_bin member function to efficiency class that automatically merges bins such that all bins have more than n total events
- Remove high range bin arrays from jetMet_analyzer
- Tidy up binning
- Checked that the efficiencies are the same as before adding this functionality for 10k events, and when setting min events to -1 
=> Dynamic binning for efficiencies

Makefile, update_release.py
Noticed that the package version is not updated when we make release &rarr; fixed.
Also, since github_changelog slightly changed how it handles the base file, updated our script for doing it instead.
=> Improving "make release" scripts

bin/cmsl1t_batch, bin/cmsl1t_dirty_batch, cmsl1t/io/eventreader.py, cmsl1t/producers/jets.py, config/efficiencies.yaml, config/ntuple_content_AODRAWEMU.yaml, config/ntuple_content_RAWEMU.yaml, config/rates.yaml
- Sort reco jets by etCorr
- Check jet bx == 0,
- Fix batch sub by loading ntuple library,
- Add merge command printout at end of batch submission,
- Remove vertex debug printout
- Include most common use case ntuple maps, RAWEMU, and AODRAWEMU
=> Sort reco jets by etCorr, check jet bx == 0, fix batch sub

cmsl1t/analyzers/HW_Emu_jetMet_rates.py, cmsl1t/plotting/base.py, cmsl1t/plotting/rate_vs_pileup.py, cmsl1t/plotting/rates.py
Fixes #150
This was harder than expected.
- implemented new Plotter function `get_stats` which returns a DataFrame
- added printout to `HW_Emu_jetMet_rates.finalize()`
- histogram statistics are stored in CSV files for future use
```
Histogram collection: RatesPlot
+--------------------------+---------+------------+---------------+---------------+--------------+---------------+-------------+--------------+
| identifier               |   total |   overflow | bin 120-200   | bin 200-320   | bin 80-100   | bin 100-120   | bin 35-90   | bin 90-120   |
|--------------------------+---------+------------+---------------+---------------+--------------+---------------+-------------+--------------|
| L1 HT; PU > 0            |      76 |        816 | 76.0          | 0.0           | ------       | …
```
=> Printout number of objects passing thresholds when estimating rates

Makefile, bin/cmsl1t, cmsl1t/analyzers/jetMet_analyzer.py, cmsl1t/config.py, cmsl1t/filters/__init__.py, cmsl1t/filters/jets_vectorized.py, cmsl1t/filters/luminosity.py, cmsl1t/io/eventreader.py, cmsl1t/jet.py, cmsl1t/producers/jets_vectorized.py, cmsl1t/producers/l1sums_vectorized.py, config/all2017.yaml, requirements.txt, test/filters/test_luminosity.py, test/filters/test_masks.py, test/io/test_uproot_event.py, test/test_config.py, test/test_jet_vectorized.py, test/test_numpy.py
Fixes #169 - filters are now treated like analyzers and producers and are run after producers and before analyzers
- introduces UprootEvent + mask
- replaces Lumifilter with vectorized version
- adds `filters` keyword to config
- removes lumi filter from jetAnalyzer
=> Global filters for events

.travis.yml, cmsl1t/__init__.py, cmsl1t/analyzers/demo_analyzer.py, cmsl1t/analyzers/jetMet_analyzer.py, cmsl1t/collections/__init__.py, cmsl1t/collections/base.py, cmsl1t/collections/by_pileup.py, cmsl1t/collections/efficiency.py, cmsl1t/collections/resolution.py, cmsl1t/collections/vectorized.py, cmsl1t/config.py, cmsl1t/playground/eventreader.py, cmsl1t/playground/resolution.py, cmsl1t/producers/met.py, cmsl1t/producers/met_vectorized.py, config/demo.yaml, requirements.txt, test/collections/test_baseHistcollection.py, test/collections/test_boost_histogram.py, test/collections/test_vectorized.py
Fixes #39, #171
Introduces `VectorizedHistCollection` that adds two things w.r.t. `BaseHistCollection`:
- access multiple histograms at once
- fill multiple histograms at once
Accessing `collection[pileup]` with `pileup = [1, 12, 1, 50]` will automatically return the histograms for the correct pileup bins (not values). This part is generalized through the `VectorizedBinProxy`.
Filling histograms can be done with either `scalar`, `numpy.ndarray` or `awkward.JaggedArray`.
`VectorizedHistCollection` also introduces some experimental functionality, e.g. `execute_before_write`.
The `execute_before_write` parameter can be used to schedule function calls before the collection is written to disk. E.g. this could replace the EfficiencyCollection's `_calculateEfficiencies` call (i.e. a step towards …
=> New histogram collection: VectorizedHistCollection

requirements.txt
Need to restrict pytest to earlier than version 4, otherwise setup doesn't work.  more-itertools also then needs restricting to earlier version (<6)
=> Restrict version of pytest and dependent more-itertools

cmsl1t/analyzers/HW_Emu_jetMet_rates.py, config/rates.yaml
Now print out thresholds for more than one menu rate supplied in the config. 
Also update rates config to use multiple thresholds.
=> Show thresholds for multiple menu rates, save output to file

cmsl1t/analyzers/BaseAnalyzer.py
Small bugfix for the -r reloading histograms from root files option.
Variable wasn't assigned when simply reloading histograms and not comparing/overlaying multiple sets of histograms.
=> Bugfix for reloading histograms
