.travis.yml
bin/env.sh
ci/Dockerfile
cmsl1t/collections/efficiency.py
cmsl1t/playground/cache.py
cmsl1t/playground/eventreader.py
cmsl1t/playground/makeJetResolutions.py
cmsl1t/playground/studyTower28MET.py
cmsl1t/recalc/met.py
test/playground/test_cachedTree.py

As this project is starting to be developed by people other than me, I've added some basic tests and syntax (PEP8) checks.
@jimbrooke : please set up a travis-ci hook before merging.

Adding continuous integration

---

bin/run_benchmark
cmsl1t/utils/timers.py

This is a nice decorator, and it would be useful to have access to from elsewhere in the code.

Move timerfunc from run_benchmark into a util file

---

.gitmodules
Makefile
bin/run_benchmark

In preparation for the first config draft, I've adjusted the legacy config for easier templating.

Fixing issue #22

---

CHANGELOG.md
bin/env.sh

A stupid typo was killing the PATH, now fixed.

Fixing issue 23

---

bin/cmsl1t
cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/analyzers/energy_sums_efficiencies.py
cmsl1t/analyzers/jet_efficiencies.py
cmsl1t/analyzers/jet_rates.py
cmsl1t/analyzers/jet_resolution.py
cmsl1t/analyzers/study_tower28_met.py
cmsl1t/collections/by_pileup.py
cmsl1t/collections/resolution.py
cmsl1t/filters/__init__.py
cmsl1t/playground/cache.py
cmsl1t/playground/eventreader.py
cmsl1t/playground/makeJetResolutions.py
config/energy_sums_efficiencies.yaml
config/jet_efficiencies.yaml
config/jet_rates.yaml
config/jet_resolutions.yaml
config/study_tower28_met.yaml
test/analyzers/test_jet_rates.py
test/collections/test_resolutionCollection.py

Solving issue #8 
Overview of migrated scripts:

Migrating legacy analyzers

---

bin/cmsl1t
cmsl1t/analyzers/study_met.py
cmsl1t/config.py
cmsl1t/hist/binning.py
cmsl1t/hist/factory.py
cmsl1t/hist/hist_collection.py
cmsl1t/playground/cache.py
cmsl1t/plotting/efficiency.py
cmsl1t/recalc/met.py
cmsl1t/utils/draw.py
test/hist/test_histogramCollection.py

The main purpose of this PR is to introduce a proper Plotter, namely the efficiency plots.
It makes use of the histogram collection introduced in PR #32.
Several other changes have snuck in with this one I'm afraid:
- Binning classes are now described in a separate module to the histogram collection
- The histogram collection and histogram factory classes have been quite heavily debugged, and as a result have had several changes.  The unit tests for these classes are unchanged and (should) still pass.
- A new util class for drawing collections of histograms and applying standard aesthetics has been added. At this point in time there are no unit tests for this.
- The returned object from the MET recalculation objects has been wrapped in an easier interface to get the MET magnitude, etc.

WIP: implement first real plotter

---

cmsl1t/hist/binning.py
cmsl1t/hist/factory.py
cmsl1t/recalc/met.py
cmsl1t/utils/draw.py
test/recalc/test_met.py

PR #37 was merged early by mistake. This PR adds in the final missing commits that implement some of the requested changes there.

Add final polish to efficiency plotter and related code

---

cmsl1t/recalc/jet_matching.py
test/recalc/test_jet_match.py

Add jet matching algorithm

---

cmsl1t/analyzers/demo_analyzer.py
cmsl1t/analyzers/energy_sums_efficiencies.py
cmsl1t/analyzers/study_tower28_met.py
cmsl1t/playground/eventreader.py
cmsl1t/recalc/met.py

Also fixed the analyser access of `recalc.met`

Fixing issue 41: execute cmsl1t from anywhere

---

bin/cmsl1t
bin/run_benchmark
cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/analyzers/demo_analyzer.py
cmsl1t/analyzers/energy_sums_efficiencies.py
cmsl1t/analyzers/jet_efficiencies.py
cmsl1t/analyzers/jet_rates.py
cmsl1t/analyzers/jet_resolution.py
cmsl1t/analyzers/legacy_analyzer.py
cmsl1t/analyzers/study_met.py
cmsl1t/analyzers/study_tower28_met.py
cmsl1t/playground/eventreader.py
config/legacy/demo.yaml

This is the first part of solving issue #6, next and final piece is the validation analyzer.
To be merged after #46.

Support to run legacy analysers in the new framework

---

cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/analyzers/study_met.py
cmsl1t/plotting/base.py
cmsl1t/plotting/efficiency.py
cmsl1t/utils/fit_efficiency.py

This PR adds a base class for Plotters, and improves the base class for Analyzers.
The rest of the code has been updated to use these and the new methods they contain.

Improve Base classes for Analyzers and Plotters

---

.dockerignore
README.md
bin/env.sh
conda_requirements.txt
docker-compose.yaml
docker/Dockerfile
docker/cdw
requirements.txt

Added instructions to be able to test HTCondor submission locally (and even in travis-CI if wanted).
Replacement for #61

Docker for HTCondor testing

---

bin/cmsl1t
config/weekly_checks.yaml
requirements.txt

Added `config/weekly_checks.yaml` to the project which currently analyses the efficiency of energy sums and jets.
Neither energy sum nor jets analysers currently use the new plotting functions in `cmsl1t.plotting`.

First version of weekly checks config

---

cmsl1t/plotting/efficiency.py
test/plotting/test_efficiency.py

This should fix the issue observed by Alex Titterton.  I've added a unit test to debug and help check this issue in the future.
I'm targeting the weekly checks branch with this, but really it should go into Master as well, given that it's a bug fix.

Fix the Efficiency plotter which was giving non-physical looking turnons

---

cmsl1t/hist/binning.py
cmsl1t/plotting/base.py
cmsl1t/plotting/efficiency.py
test/plotting/test_efficiency.py

Who would have thought the efficiency curves would be so tricksy... But I think this should have them working properly.  At least when I run on a bunch of events things seem ok and the additional unit tests suggest the same.

Fix another issue with the efficiency curves

---

bin/cmsl1t_dirty_batch
cmsl1t/analyzers/weekly_analyzer.py
cmsl1t/plotting/onlineVsOffline.py
cmsl1t/recalc/resolution.py
config/weekly_checks.yaml

This PR implements the weekly_analyzer used for the weekly checks of the jet sums.  
Should be merged after #76.

"Final" PR to add all changes for weekly checks

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

As taken from
https://github.com/rhysd/dot-github
Feedback regarding the content is welcome.

Github templates for issues and pull requests

---

Makefile
bin/env.sh
docs/tutorial.rst
docs/tutorial/quickstart.rst

This is part 1 of pulling Alex' PR #89 apart for easier review and merging.
Part 1 includes:
- fixes to `bin/env.sh`
- updates to `Makefile`
- adding quickstart guide to the documentation (`QUICKSTART.md` &rarr; `docs/tutorial/quickstart.rst`)

Breakdown of PR 89 - part 1

---

bin/get_l1Analysis
cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/plotting/resolution.py
cmsl1t/utils/draw.py

This is part 2 of pulling Alex' PR #89 apart for easier review and merging.
Part 2 includes simple changes with minor adjustments:
- default plot output format
- plotting adjustments
- main CMSSW repo to pull data formats from
Part 3 will include moderate changes with adjustments while the last part, part 4, will include all the new files with adjustments based on part 2 and 3 (if needed).

Breakdown of PR 89 - part 2

---

cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/plotting/efficiency.py
cmsl1t/plotting/onlineVsOffline.py
cmsl1t/plotting/resolution_vs_X.py

This is part 3 of pulling Alex' PR #89 apart for easier review and merging.
Part 3 includes changes to **efficiency, online vs offline and resolution vs X plots**.
It also adds a **new variable for analyzers**, `self.puBins` that is read from the config.

Breakdown of PR 89 - part 3

---

cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/analyzers/offline_met_analyzer.py
cmsl1t/analyzers/weekly_analyzer.py
config/offline_met_studies.yaml

This is last part, part 4, of pulling Alex' PR #89 apart for easier review and merging.
It includes:

Breakdown of PR 89 - part 4

---

cmsl1t/analyzers/offline_met_analyzer.py

Fixes #97 
Added *_Emu plotters and JetET_* plotters.

Added JetET plotters to offline MET analyser, no longer crashes

---

bin/cmsl1t
bin/get_l1Analysis
cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/analyzers/HW_Emu_constant_rate_turnons.py
cmsl1t/analyzers/jetMet_analyzer.py
cmsl1t/analyzers/offline_met_analyzer.py
cmsl1t/analyzers/weekly_analyzer.py
cmsl1t/energySums.py
cmsl1t/hist/binning.py
cmsl1t/playground/eventreader.py
cmsl1t/utils/__init__.py
cmsl1t/utils/draw.py
config/jet_rates.yaml
requirements.txt
test/hist/test_binning.py
test/playground/test_eventreader.py

This PR build upon #107 to replace #106.
After this one only the following files need work:
- cmsl1t/playground/lumifilters.py
- cmsl1t/plotting/efficiency.py
- cmsl1t/plotting/rates.py
- cmsl1t/plotting/resolution.py

Config, Event and hist related parts of #106

---

README.md

Adds rebase command to the README instructions

Add rebase command to README

---

cmsl1t/playground/eventreader.py

Remove @cached and corresponding import

---

cmsl1t/analyzers/jetMet_analyzer.py

Crash due to lumi filter implementation not yet updated in jetMet_analyzer. Updated to match implementation in HW_Emu_jetMet_rates.

Fix lumi filter in jetMet_analyzer

---

Makefile
config/efficiencies.yaml
config/gen.yaml
config/rateVsPU.yaml
config/rates.yaml

Adds configs for 4 main run modes:
- Efficiencies (hw vs emu)
- Rates (hw vs emu)
- MC (gen)
- Rate vs pu (hw vs emu)
Also move test files to common dir. 

Add config yamls for 4 main modes

---

cmsl1t/plotting/efficiency.py

Small bug fix for inclusive pileup efficiency plots

Bug fix to efficiencies

---

bin/create-map-file
cmsl1t/io/mapfile.py
test/io/test_mapfile.py

Depends on #112.
Extracted the mapfile changes of #80 into this PR.

[IO] Moving code from create-map-file to cmsl1t.io.mapfile for easier testing

---

cmsl1t/io/eventreader.py
cmsl1t/producers/jets.py
cmsl1t/producers/match.py
cmsl1t/producers/met.py
cmsl1t/utils/decorators.py
test/io/test_eventreader.py

Bringing over all the new files from #85 with the feedback received there.
Changes to existing files to integrate these into the current analysis will come in a later PR and will require rigurous testing before merging.

Remaining new files from PR #85

---

cmsl1t/utils/module.py

Added error reporting to utils.module.exists (issue #88)

---

cmsl1t/plotting/efficiency.py
cmsl1t/plotting/resolution.py

- Sets plot limits dynamically
- Plots lines at threshold values

More plot formatting

---

bin/cmsl1t
cmsl1t/analyzers/BaseAnalyzer.py
cmsl1t/analyzers/HW_Emu_jetMet_rates.py
cmsl1t/analyzers/demo_analyzer.py
cmsl1t/analyzers/inspector.py
cmsl1t/analyzers/jetMet_analyzer.py
cmsl1t/analyzers/legacy_analyzer.py
cmsl1t/analyzers/study_tower28_met.py
cmsl1t/analyzers/weekly_analyzer.py
cmsl1t/config.py
cmsl1t/producers/base.py
cmsl1t/producers/jets.py
cmsl1t/producers/l1sums.py
cmsl1t/producers/met.py
config/all2017.yaml
config/demo.yaml
config/efficiencies.yaml
config/gen.yaml
config/offline_met_studies.yaml
config/rateVsPU.yaml
config/rates.yaml
config/study_tower28_met.yaml
config/weekly_checks.yaml
test/test_config.py

Fixes #47
Also:
- simplified syntax for analysers and producers: additional params are now always included

Config scope reduction for analyzers and producers

---

.travis.yml
bin/cmsl1t
ci/integration-test.sh
ci/test.sh
cmsl1t/analyzers/HW_Emu_jetMet_rates.py
cmsl1t/analyzers/jetMet_analyzer.py
cmsl1t/analyzers/study_tower28_met.py
cmsl1t/analyzers/weekly_analyzer.py
cmsl1t/filters/__init__.py
cmsl1t/filters/muonfilter.py
cmsl1t/jet.py
cmsl1t/producers/gensums.py
config/all2017.yaml
config/demo.yaml
config/efficiencies.yaml
config/gen.yaml
config/ntuple_content_mc.yaml
config/offline_met_studies.yaml
config/rateVsPU.yaml
config/rates.yaml
config/study_tower28_met.yaml
config/weekly_checks.yaml
docker-compose.yaml

Integration testing for data worfllow & fixes for #144

---

bin/get_l1Analysis
cmsl1t/analyzers/HW_Emu_jetMet_rates.py
cmsl1t/analyzers/jetMet_analyzer.py
cmsl1t/collections/resolution.py
cmsl1t/config.py
cmsl1t/hist/binning.py
cmsl1t/hist/hist_collection.py
cmsl1t/io/__init__.py
cmsl1t/playground/eventreader.py
cmsl1t/utils/__init__.py
cmsl1t/utils/fit_efficiency.py

Fixing current travis build issues

---

cmsl1t/analyzers/jetMet_analyzer.py

Removes pileup selection in jetMetAnalyzer

Remove pileup selection in jetMetAnalyzer

---

bin/get_l1Analysis
cmsl1t/analyzers/HW_Emu_jetMet_rates.py
cmsl1t/analyzers/jetMet_analyzer.py
cmsl1t/plotting/efficiency.py
cmsl1t/plotting/rates.py
cmsl1t/producers/jets.py
cmsl1t/utils/draw.py
config/ntuple_content_mc.yaml
config/pfJetEff.yaml
config/pfJetRates.yaml

Update to add functionality for phase 2 pf jets performance studies.

Phase 2 PF Jet update

---

cmsl1t/analyzers/HW_Emu_jetMet_rates.py
cmsl1t/analyzers/jetMet_analyzer.py
cmsl1t/plotting/rates.py
cmsl1t/utils/hist.py
cmsl1t/utils/root_glob.py
requirements.txt

- Adds the xrootd glob function from fast curator to parse wildcards in xrootd paths
- Update/ tidy up rate normalisation

Add xrootd glob

---

requirements.txt

Fix pytest version to 3.5.0

---

bin/get_l1Analysis
config/ntuple_content_mc.yaml

Adds the L1Ntuple PhaseII data format for use with standard workflow

Add phase2 data format

---

cmsl1t/analyzers/HW_Emu_jetMet_rates.py
cmsl1t/analyzers/jetMet_analyzer.py
cmsl1t/plotting/efficiency.py
cmsl1t/plotting/rate_vs_pileup.py
cmsl1t/plotting/rates.py
cmsl1t/plotting/resolution.py

Implements running comparisons using multiple sets of input ntuples for emulator vs emulator in addition to unpacked vs unpacked

Implement emulator vs emulator comparisons
